# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set the environment variables
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD sulav
ENV POSTGRES_DB db

# Expose the PostgreSQL port
EXPOSE 5432

# Start the PostgreSQL service
CMD ["postgres"]
